-- Simple todos table for Supabase (public schema)
-- Run this in Supabase SQL editor.

create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  title text not null,
  done boolean not null default false,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Basic row level security policy: allow authenticated users full access to their own todos.
-- For very first learning project, you can temporarily disable RLS, but it's recommended to keep it ON.

alter table public.todos enable row level security;

-- Example simple policies for learning (adjust for real apps):

create policy "Todo read access" on public.todos
  for select
  using (true);

create policy "Todo insert access" on public.todos
  for insert
  with check (true);

create policy "Todo update access" on public.todos
  for update
  using (true)
  with check (true);

create policy "Todo delete access" on public.todos
  for delete
  using (true);
